# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled2.ui'
#
# Created by: PyQt5 UI code generator 5.15.8
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(650, 175)
        Form.setMinimumSize(QtCore.QSize(650, 175))
        Form.setMaximumSize(QtCore.QSize(650, 175))
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.formLayout_2 = QtWidgets.QFormLayout()
        self.formLayout_2.setObjectName("formLayout_2")
        self.Label = QtWidgets.QLabel(Form)
        self.Label.setObjectName("Label")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.Label)
        self.LineEdit = QtWidgets.QLineEdit(Form)
        self.LineEdit.setObjectName("LineEdit")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.LineEdit)
        self.Label_2 = QtWidgets.QLabel(Form)
        self.Label_2.setObjectName("Label_2")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.Label_2)
        self.LineEdit_2 = QtWidgets.QLineEdit(Form)
        self.LineEdit_2.setObjectName("LineEdit_2")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.LineEdit_2)
        self.Label_3 = QtWidgets.QLabel(Form)
        self.Label_3.setObjectName("Label_3")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.Label_3)
        self.LineEdit_3 = QtWidgets.QLineEdit(Form)
        self.LineEdit_3.setObjectName("LineEdit_3")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.LineEdit_3)
        self.Label_4 = QtWidgets.QLabel(Form)
        self.Label_4.setObjectName("Label_4")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.Label_4)
        self.LineEdit_4 = QtWidgets.QLineEdit(Form)
        self.LineEdit_4.setObjectName("LineEdit_4")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.LineEdit_4)
        self.Label_5 = QtWidgets.QLabel(Form)
        self.Label_5.setObjectName("Label_5")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.Label_5)
        self.LineEdit_5 = QtWidgets.QLineEdit(Form)
        self.LineEdit_5.setObjectName("LineEdit_5")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.LineEdit_5)
        self.verticalLayout.addLayout(self.formLayout_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout.addWidget(self.pushButton)
        self.pushButton_2 = QtWidgets.QPushButton(Form)
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout.addWidget(self.pushButton_2)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.Label.setText(_translate("Form", "Марка"))
        self.Label_2.setText(_translate("Form", "Серийный номер"))
        self.Label_3.setText(_translate("Form", "Мощность"))
        self.Label_4.setText(_translate("Form", "Государственный регистрационный знак"))
        self.Label_5.setText(_translate("Form", "Гаражный номер"))
        self.pushButton.setText(_translate("Form", "Добавить"))
        self.pushButton_2.setText(_translate("Form", "Отмена"))
